name: eanic
description: A cross-platform, pure-Dart package to read and write ID3 tags.
version: 0.1.0
homepage: https://github.com/kgyf/eanic

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.7
